name: Bug Report
description: Create a bug report
title: "Bug:"
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      description: What is happening? Include a clear description of the behaviour that is incorrect or unexpected.
      label: Bug Description
      value:
    validations:
      required: true
  - type: dropdown
    id: source
    attributes:
      label: Source
      description: Where the bug was identified
      options:
        - External (reported by user, partner team, etc.)
        - Internal (found by a member of a Justice Data Platform team, monitoring, or automated tests)
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      description: Step-by-step instructions to reliably recreate the issue.
      label: Steps to Reproduce
      placeholder: 1. Go to '...'

        2. Click on '....'

        3. Scroll down to '....'

        4. See error...
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      description: What should happen if the system behaved correctly.
      label: Expected Behaviour
      value:
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      description: Any additional notes such as logs, screenshots, environment details, links, or related PRs.
      label: Additional Context
      value:
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      description: Where the bug occurred (e.g., dev, test, prod, cluster name, account, etc.).
      label: Environment
      value:
    validations:
      required: false
  - type: textarea
    id: severity
    attributes:
      description: User impact or urgency level details.
      label: Severity/Impact
      value:
    validations:
      required: false
