name: Story
description: Create a Story
title: ""
labels: ["story"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the fields below to create a new Story.
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Clear user story format
      placeholder: "As a… *[who is the user?]*

        I want… *[what does the user want to do?]*

        So that… *[why does the user want to do this?]*"
      value: "As a…

        I want…

        So that…"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Testable, clear conditions of success
      placeholder: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description/Context
      description: Brief explanation to support understanding. What's the need? Why now?
      placeholder: Provide context for this story...
    validations:
      required: true
  - type: textarea
    id: functional-requirements
    attributes:
      label: Functional Requirements
      description: Only if essential. High-level capability needed for this story.
      placeholder: |
        -
    validations:
      required: false
  - type: textarea
    id: non-functional-requirements
    attributes:
      label: Non-Functional Requirements
      description: Performance/security/usability expectations
      placeholder: |
        -
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Links to other stories, spikes, teams
      placeholder: |
        -
    validations:
      required: false
  - type: input
    id: useful-contacts
    attributes:
      description: SMEs, reviewers, stakeholders (if useful)
      placeholder: Insert useful contacts here
      label: Useful Contacts
      value:
    validations:
      required: false
  - type: textarea
    id: technical-notes
    attributes:
      description: Useful ONLY when needed
      label: Technical Notes / Additional Information
      value:
    validations:
      required: false
  - type: textarea
    id: dod
    attributes:
      description: Small checklist for completion of this story
      label: Definition of Done
      value: |
        - [ ] Documentation has been written / updated
        - [ ] README has been updated
        - [ ] User docs have been updated
        - [ ] Another team member has reviewed
        - [ ] Tests are green
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        [How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
