name: Task
description: Create a Task
title: "[Task]:"
labels: ["task"]

body:
  - type: textarea
    id: description
    attributes:
      description: A clear explanation of what needs to happen and why. Keep concise but meaningful.
      label: Task Description
      value:
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      description: What must be true for the task to be complete. Should be testable and unambiguous.
      label: Acceptance Criteria
      placeholder: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      description: Steps or subtasks to complete this task. Useful for technical and operational work.
      label: Steps to Address
      placeholder: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      description: Other tickets, teams, or prerequisites this task relies on
      label: Dependencies
      placeholder: |
        -
    validations:
      required: false
  - type: input
    id: useful-contacts
    attributes:
      description: SMEs, reviewers, or engineers who can support or approve work
      label: Useful Contacts
      placeholder: Insert useful contacts here
    validations:
      required: false
  - type: textarea
    id: technical-notes
    attributes:
      description: Logs, error messages, long-form technical guidance, architectural details, root cause notes, commands, links
      label: Technical Notes / Additional Info
      value:
    validations:
      required: false
  - type: textarea
    id: links-references
    attributes:
      description: Slack threads, runbooks, GitHub Issues, architecture docs, pipelines, diagrams
      label: Links & References
      placeholder: |
        -
    validations:
      required: false
