---
name: Spell Check

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@e22f0c9cafa7528d5594c19fe1401ec893424272 # v4.0.4
