---
name: Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@7f9f1fc18fcddd41c08a33be1e4e57cb8065a0cf # v4.0.0
    with:
      super-linter-variables: |
        {
          "VALIDATE_CSS": false,
          "VALIDATE_JSCPD": false
        }
